services:
  manga-app:
    build: .
    ports:
      - "8501:8501"
      - "8000:8000"
    volumes:
      # ホスト側の ./app/data を コンテナ内の /app/app/data に繋ぐ
      - ./app/data:/app/app/data 
      # 開発中にコードを即時反映させたい場合
      - .:/app 
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"